name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@1fb06179c376b10a4da4c778e1c794ef5a0df302 # 13.3
        with:
          cli: latest
          bb: latest
          clj-kondo: latest

      - name: Cache Clojure dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: clj-${{ hashFiles('deps.edn') }}
          restore-keys: clj-

      - name: Run tests
        run: bb test

      - name: Run linter
        run: bb lint
